[project]
name = "airflow-lab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "apache-airflow>=3.0.3",
    "apache-airflow-providers-fab>=2.3.0",
]
